rift_run_wizards:
    type: rest
    resource: RiftRunBundle\Controller\WizardsController
rift_run_posts:
    type: rest
    resource: RiftRunBundle\Controller\PostsController
rift_run_search:
    type: rest
    resource: RiftRunBundle\Controller\SearchController
