parameters:
    configured_pipelines:
          processFormPipe: 'RiftRunBundle\CommandBus\Pipelines\ProcessFormPipe'
          transformDTOPipe: 'RiftRunBundle\CommandBus\Pipelines\TransformDTOPipe'
          fetchPipeline:  'RiftRunBundle\Services\Pipelines\FetchPipeline'

services:
    league_pipeline_builder:
        class: League\Pipeline\PipelineBuilder

    pipeline_manager:
        class: RiftRunBundle\CommandBus\Pipelines\PipelineManager
        arguments:
            - '@league_pipeline_builder'
            - '%configured_pipelines%'
        calls:
            - [ setContainer, [ '@service_container' ] ]

    create_post_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\CreatePostCommandHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pipeline_manager'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\CreatePost }

    # QueryBuilder Specification
    all_posts_specification:
        class: RiftRunBundle\ORM\Specification\AllPostsSpecification

    # Query Services
    fetch_posts_service:
        class: RiftRunBundle\Services\PostsQueryService
        arguments:
            - '@doctrine'
            - '@jms_serializer'
            - '@pager_fanta_factory'

    fetch_post_service:
        class: RiftRunBundle\Services\PostQueryService
        arguments:
            - '@doctrine'

    # Helper
    form_errors_helper:
        class: RiftRunBundle\Helpers\FormErrors

    # External libs
    pager_fanta_factory:
        class: Hateoas\Representation\Factory\PagerfantaFactory