services:
    tactitian.middleware.event_emmiter:
        class: League\Tactician\CommandEvents\EventMiddleware

    pagerfanta_factory_library:
        class: Hateoas\Representation\Factory\PagerfantaFactory

    pagerfanta_factory:
        class: RiftRunBundle\Factories\PagerfantaFactory

    singletype_factory:
        class: RiftRunBundle\Factories\SingleTypeFactory
        calls:
            - [ setContainer, [ '@service_container' ]]

    create_post_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\CreatePostCommandHandler
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\CreatePost }

    paginate_posts_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\PaginatePostsCommandHandler
        arguments:
            - '@doctrine'
            - '@pagerfanta_factory'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\PagerfantaPaginate }

    process_form_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\ProcessFormCommandHandler
        arguments:
            - '@form.factory'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\ProcessPostForm }

    # QueryBuilder Specification
    all_posts_specification:
        class: RiftRunBundle\ORM\Specification\AllPostsSpecification
