services:
    tactitian.middleware.event_emmiter:
        class: League\Tactician\CommandEvents\EventMiddleware

    pagerfanta_factory_library:
        class: Hateoas\Representation\Factory\PagerfantaFactory

    pagerfanta_factory:
        class: RiftRunBundle\Factories\PagerfantaFactory

    create_post_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\CreatePostCommandHandler
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\CreatePost }

    paginate_posts_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\PaginatePostsCommandHandler
        arguments:
            - '@doctrine'
            - '@pagerfanta_factory'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\PagerfantaPaginate }

    process_form_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\ProcessFormCommandHandler
        arguments:
            - '@form.factory'
            - '@default_event_dispatcher'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\ProcessPostForm }

    fetch_single_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\FetchSingleCommandHandler
        arguments:
            - '@doctrine'
            - '@jms_serializer'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\FetchSingle }

    transform_dto_to_model_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\TransformDTOModelCommandHandler
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\DTOAdapter }

    # QueryBuilder Specification
    all_posts_specification:
        class: RiftRunBundle\ORM\Specification\AllPostsSpecification

    # Listeners
    process_form_listener:
        class: RiftRunBundle\CommandBus\Listeners\CreateFormListener
        arguments:
            - '@tactician.commandbus.default'
        tags:
            - { name: tactician.listener, event: hydrate.form, method: handle }