services:
    pagerfanta_factory_library:
        class: Hateoas\Representation\Factory\PagerfantaFactory

    pagerfanta_factory:
        class: RiftRunBundle\Factories\PagerfantaFactory

    pipeline:
        class: League\Pipeline\Pipeline

    process_form_pipeline:
        class: RiftRunBundle\CommandBus\Pipelines\ProcessFormPipe
        arguments:
            - '@form.factory'

    transform_dto_pipeline:
        class: RiftRunBundle\CommandBus\Pipelines\TransformDTOPipe

    create_post_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\CreatePostCommandHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pipeline'
            - '@process_form_pipeline'
            - '@transform_dto_pipeline'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\CreatePost }

    paginate_posts_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\PaginatePostsCommandHandler
        arguments:
            - '@doctrine'
            - '@pagerfanta_factory'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\PagerfantaPaginate }

    fetch_single_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\FetchSingleCommandHandler
        arguments:
            - '@doctrine'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\FetchSingle }

    # Subhandlers
    process_form_subhandler:
        class: RiftRunBundle\CommandBus\SubHandlers\ProcessFormHandler
        arguments:
            - '@form.factory'
            - '@form_errors_helper'

    transform_dto_subhandler:
        class: RiftRunBundle\CommandBus\SubHandlers\TransformDTOHandler

    # QueryBuilder Specification
    all_posts_specification:
        class: RiftRunBundle\ORM\Specification\AllPostsSpecification

    # Helper
    form_errors_helper:
        class: RiftRunBundle\Helpers\FormErrors