services:
    tactitian.middleware.event_emmiter:
        class: League\Tactician\CommandEvents\EventMiddleware

    pagerfanta_factory_library:
        class: Hateoas\Representation\Factory\PagerfantaFactory

    pagerfanta_factory:
        class: RiftRunBundle\Factories\PagerfantaFactory

    create_post_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\CreatePostCommandHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@process_form_subhandler'
            - '@transform_dto_subhandler'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\CreatePost }

    paginate_posts_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\PaginatePostsCommandHandler
        arguments:
            - '@doctrine'
            - '@pagerfanta_factory'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\PagerfantaPaginate }

    fetch_single_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\FetchSingleCommandHandler
        arguments:
            - '@doctrine'
            - '@jms_serializer'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\FetchSingle }

    # Subhandlers
    process_form_subhandler:
        class: RiftRunBundle\CommandBus\SubHandlers\ProcessFormHandler
        arguments:
            - '@form.factory'

    transform_dto_subhandler:
        class: RiftRunBundle\CommandBus\SubHandlers\TransformDTOHandler

    # QueryBuilder Specification
    all_posts_specification:
        class: RiftRunBundle\ORM\Specification\AllPostsSpecification