services:
    pagination_factory:
        class: RiftRunBundle\Factories\PaginationFactory
        arguments:
            - @request_stack
            - @all_posts_specification
        calls:
            - [ setContainer, [ @service_container ]]

    singletype_factory:
        class: RiftRunBundle\Factories\SingleTypeFactory
        calls:
            - [ setContainer, [ @service_container ]]

    create_post_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\CreatePostCommandHandler
        arguments:
            - @form.factory
            - @doctrine.orm.entity_manager
            - @post_form_type
            - @request_stack
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\CreatePost }

    # FormTypes
    post_form_type:
        class: RiftRunBundle\Forms\PostType

    # QueryBuilder Specification
    all_posts_specification:
        class: RiftRunBundle\ORM\Specification\AllPostsSpecification
