services:
    pagerfanta_factory_library:
        class: Hateoas\Representation\Factory\PagerfantaFactory

    pagerfanta_factory:
        class: RiftRunBundle\Factories\PagerfantaFactory

    singletype_factory:
        class: RiftRunBundle\Factories\SingleTypeFactory
        calls:
            - [ setContainer, [ '@service_container' ]]

    create_post_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\CreatePostCommandHandler
        arguments:
            - '@form.factory'
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\CreatePost }

    paginate_posts_command_handler:
        class: RiftRunBundle\CommandBus\Handlers\PaginatePostsCommandHandler
        arguments:
            - '@doctrine'
            - '@pagerfanta_factory'
        tags:
            - { name: tactician.handler, command: RiftRunBundle\CommandBus\Commands\PagerfantaPaginate }

    # QueryBuilder Specification
    all_posts_specification:
        class: RiftRunBundle\ORM\Specification\AllPostsSpecification
