services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: riftrun }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
