<?php

namespace App\ORM\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * SearchQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchQueryRepository extends EntityRepository
{
    public function match(Callable $criteria, $searchCriteria)
    {
        $queryBuilder = $this->createQueryBuilder('searchQuery');

        return call_user_func_array($criteria, [$queryBuilder, $searchCriteria]);
    }
}
