services:
    standard_orm_purger:
        class: Doctrine\Common\DataFixtures\Purger\ORMPurger

    load_fixtures_command_handler:
        class: DevHelperBundle\Command\Handlers\LoadFixturesCommandHandler
        arguments:
            - @nelmio_loader_factory
        tags:
            - { name: tactician.handler, command: DevHelperBundle\Command\Commands\LoadFixtures }

    clear_fixtures_command_handler:
        class: DevHelperBundle\Command\Handlers\DatabaseClearCommandHandler
        arguments:
            - @doctrine.orm.entity_manager
            - @standard_orm_purger
        tags:
            - { name: tactician.handler, command: DevHelperBundle\Command\Commands\ClearDatabase }

    create_schema_command_handler:
        class: DevHelperBundle\Command\Handlers\CreateSchemaCommandHandler
        tags:
            - { name: tactician.handler, command: DevHelperBundle\Command\Commands\CreateSchema }

    update_schema_command_handler:
        class: DevHelperBundle\Command\Handlers\UpdateSchemaCommandHandler
        tags:
            - { name: tactician.handler, command: DevHelperBundle\Command\Commands\UpdateSchema }

    load_fixtures_cli:
        class: DevHelperBundle\Cli\DatabaseSeederCommand
        tags:
            -  { name: console.command }

    clear_database_cli:
        class: DevHelperBundle\Cli\DatabaseClearCommand
        tags:
            -  { name: console.command }

    # Factories
    nelmio_loader_factory:
        class: DevHelperBundle\Factories\AliceLoaderFactory
        arguments:
            - @doctrine.orm.entity_manager