services:
    load_fixtures_command_handler:
        class: DevHelperBundle\Command\Handlers\LoadFixturesCommandHandler
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: command_handler, handles: DevHelperBundle\Command\Commands\LoadFixtures }

    clear_fixtures_command_handler:
        class: DevHelperBundle\Command\Handlers\DatabaseClearCommandHandler
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: command_handler, handles: DevHelperBundle\Command\Commands\ClearDatabase }

    create_schema_command_handler:
        class: DevHelperBundle\Command\Handlers\CreateSchemaCommandHandler
        tags:
            - { name: command_handler, handles: DevHelperBundle\Command\Commands\CreateSchema }

    update_schema_command_handler:
        class: DevHelperBundle\Command\Handlers\UpdateSchemaCommandHandler
        tags:
            - { name: command_handler, handles: DevHelperBundle\Command\Commands\UpdateSchema }

    load_fixtures_cli:
        class: DevHelperBundle\Cli\DatabaseSeederCommand
        tags:
            -  { name: console.command }

    clear_database_cli:
        class: DevHelperBundle\Cli\DatabaseClearCommand
        tags:
            -  { name: console.command }
