imports:
    - { resource: 'parameters.yml' }
    - { resource: 'security.yml' }
    - { resource: 'services.yml' }
    - { resource: 'doctrine_extensions.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: '%kernel.root_dir%/../conf/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        enable_annotations: false
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
      - '%kernel.root_dir%/templates'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: riftrun
        types:
            uuid: 'Ramsey\Uuid\Doctrine\UuidType'
        connections:
            riftrun:
                driver:   pdo_sqlite
                path:     '%database_path%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        default_entity_manager: default
        entity_managers:
            default:
                connection: riftrun
                mappings:
                    App:
                        type: yml
                        is_bundle: false
                        dir:       '%kernel.root_dir%/../conf/doctrine/riftrun'
                        prefix:    'App\Model'
                        alias:     'RiftRunners'
# FOS Rest Configuration
sensio_framework_extra:
    view:       { annotations: true }
    router:     { annotations: true}

fos_rest:
    param_fetcher_listener: force
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: force
        failed_validation: HTTP_BAD_REQUEST
    routing_loader:
        default_format: json
        include_format: false
    serializer:
        serialize_null: true
    exception:
        enabled: true

jms_serializer:
    metadata:
        cache: file
        debug: '%kernel.debug%'
        file_cache:
            dir: '%kernel.cache_dir%/jms_serializer'
        auto_detection: true
        directories:
            RiftRun:
                namespace_prefix: 'App\\DTO'
                path: '%kernel.root_dir%/conf/serializer/'

bazinga_hateoas:
    metadata:
        cache:                file
        file_cache:
            dir:              '%kernel.cache_dir%/hateoas'

tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler

nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
        paths:
            '^/v1/':
                allow_origin: ['*']
                #allow_origin: ['^http://localhost:[0-9]+', '^http://fa.local', '^http://fa.local/', '^http://riftrun.local+']
                allow_headers: ['Content-Type']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
#            '^/':
#                origin_regex: true
#                allow_origin: ['^http://localhost:[0-9]+']
#                allow_headers: ['X-Custom-Auth']
#                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#                max_age: 3600
#                hosts: ['^api\.']
