imports:
    - { resource: 'parameters.yml' }
    - { resource: 'security.yml' }
    - { resource: 'services.yml' }
    - { resource: 'services/services.yml' }
    - { resource: 'doctrine_extensions.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: '%kernel.root_dir%/../conf/routing.yml'
        strict_requirements: true
    form:            ~
    csrf_protection: ~
    validation:
        enabled: true
        enable_annotations: false
        mapping:
            paths:
                - '%kernel.root_dir%/../conf/validation'
    serializer:      { enable_annotations: false }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
      - '%kernel.root_dir%/templates'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: riftrun
        types:
            uuid: 'Ramsey\Uuid\Doctrine\UuidType'
            postId: App\Infrastructure\Post\Doctrine\Types\PostIdType
            playerCharacterId: App\Infrastructure\PlayerCharacter\Doctrine\Types\PlayerCharacterIdType
            playerId: App\Infrastructure\Player\Doctrine\Types\PlayerIdType
            searchQueryId: App\Infrastructure\SearchQuery\Doctrine\Types\SearchQueryIdType
            gameModeId: App\Infrastructure\GameMode\Doctrine\Types\GameModeIdType
        connections:
            riftrun:
                mapping_types:
                    json: string
                driver:   pdo_sqlite
                path:     '%database_path%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        # naming_strategy: doctrine.orm.naming_strategy.underscore
        default_entity_manager: default
        entity_managers:
            default:
                connection: riftrun
                mappings:
                    Post:
                        type: yml
                        is_bundle: false
                        dir:       '%kernel.root_dir%/../conf/doctrine/post'
                        prefix:    'App\Domain\Post\Model'
                        alias:     'RiftRunners'
                    Player:
                        type: yml
                        is_bundle: false
                        dir:       '%kernel.root_dir%/../conf/doctrine/player'
                        prefix:    'App\Domain\Player\Model'
                        alias:     'RiftRunners'
                    SearchQuery:
                        type: yml
                        is_bundle: false
                        dir:       '%kernel.root_dir%/../conf/doctrine/searchquery'
                        prefix:    'App\Domain\SearchQuery\Model'
                        alias:     'RiftRunners'
                    PlayerCharacter:
                        type: yml
                        is_bundle: false
                        dir:       '%kernel.root_dir%/../conf/doctrine/playercharacter'
                        prefix:    'App\Domain\PlayerCharacter\Model'
                        alias:     'RiftRunners'
                    GameMode:
                        type:       yml
                        is_bundle:  false
                        dir:        '%kernel.root_dir%/../conf/doctrine/gamemode'
                        prefix:     'App\Domain\GameMode\Model'
                        alias:      'RiftRunners'
                    GameType:
                        type:       yml
                        is_bundle:  false
                        dir:        '%kernel.root_dir%/../conf/doctrine/valueobject'
                        prefix:     'App\Domain\GameMode\ValueObject'

# FOS Rest Configuration
sensio_framework_extra:
    view:       { annotations: true }
    router:     { annotations: true }
    psr_message: { enabled: true }

#        router:      { annotations: true }
#        request:     { converters: true, auto_convert: true }
#        view:        { annotations: true }
#        cache:       { annotations: true }
#        security:    { annotations: true }
#        psr_message: { enabled: false } # Defaults to true if

fos_rest:
    versioning:
        enabled: true
        resolvers:
            query:
                parameter_name: version
            media_type:
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    param_fetcher_listener: force
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: true }
    view:
        view_response_listener: force
        formats:
            json: true
        mime_types:
            json: ['application/json', 'application/json;version=2.0']
        failed_validation: HTTP_BAD_REQUEST
    routing_loader:
        default_format: json
        include_format: false
    serializer:
        serialize_null: true
        version: 'v1'
#        groups: ['Identifier', 'Basic']
    exception:
        enabled: true
        codes:
            '\InvalidArgumentException': 400
            'Doctrine\ORM\OptimisticLockException': 409
            'Doctrine\DBAL\Exception\UniqueConstraintViolationException': 409
            'App\Domain\Common\NotFoundException': 404
        messages:
            '\InvalidArgumentException': true
            'App\Domain\Common\NotFoundException': true

jms_serializer:
    metadata:
        cache: file
        debug: '%kernel.debug%'
        file_cache:
            dir: '%kernel.cache_dir%/jms_serializer'
        auto_detection: true
        directories:
            Common:
                namespace_prefix: 'App\Domain\Common'
                path: '%kernel.root_dir%/../conf/serializer/common'
            Post:
                namespace_prefix: 'App\Domain\Post'
                path: '%kernel.root_dir%/../conf/serializer/post'
            SearchQuery:
                namespace_prefix: 'App\Domain\SearchQuery'
                path: '%kernel.root_dir%/../conf/serializer/query'
            Player:
                namespace_prefix: 'App\Domain\Player'
                path: '%kernel.root_dir%/../conf/serializer/player'
            PlayerCharacter:
                namespace_prefix: 'App\Domain\PlayerCharacter'
                path: '%kernel.root_dir%/../conf/serializer/playerCharacter'
            GameMode:
                namespace_prefix: 'App\Domain\GameMode'
                path: '%kernel.root_dir%/../conf/serializer/gameMode'

bazinga_hateoas:
    metadata:
        cache:                file
        file_cache:
            dir:              '%kernel.cache_dir%/hateoas'

tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:  ['http://localhost']
        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers: ["content-type", "authorization"]
        max_age:       3600
    paths:
        '^/': ~
