parameters:
services:
    _defaults:
        public: false
        autowire: true

    _instanceof:
        App\Services\QueryService:
            public: true
        App\CommandBus\Handlers\CreatePostCommandHandler:
            public: true
            tags:
                - { name: tactician.handler, command: App\CommandBus\Commands\CreatePost }
        App\Command\Handlers\LoadFixturesCommandHandler:
            public: true
            tags:
                - { name: tactician.handler, command: App\Command\Commands\LoadFixtures }
        App\Command\Handlers\DatabaseClearCommandHandler:
            public: true
            tags:
                - { name: tactician.handler, command: App\Command\Commands\ClearDatabase }
        App\Application\UseCase\Post\FindPostHandler:
            public: true
            tags:
                - { name: tactician.handler, command: App\Application\UseCase\Post\Find }

        Twig_ExtensionInterface:
            tags: ['twig.extension']

        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags: ['kernel.event_subscriber']

    JMS\Serializer\SerializerInterface: '@jms_serializer.serializer'
    Hateoas\Representation\Factory\PagerfantaFactory: '@pager_fanta_factory'
    Doctrine\Common\DataFixtures\Purger\PurgerInterface: '@standard_orm_purger'
    App\Factories\LoaderFactory: '@nelmio_loader_factory'
    League\Tactician\CommandBus: '@tactician.commandbus.default'

    App\:
        resource: '../src/{Services,CommandBus/Handlers,Command/Handlers}'
    App\Application\UseCase\:
        resource: '../src/Application/UseCase'
    App\UI\Rest\Controller\:
        resource: '../src/UI/Rest/Controller'
        public: true

    standard_orm_purger:
        class: Doctrine\Common\DataFixtures\Purger\ORMPurger

    pager_fanta_factory:
        class: Hateoas\Representation\Factory\PagerfantaFactory

    load_fixtures_cli:
        class: App\Cli\DatabaseSeederCommand
        tags:
            -  { name: console.command }

    clear_database_cli:
        class: App\Cli\DatabaseClearCommand
        tags:
            -  { name: console.command }

    # Factories
    nelmio_loader_factory:
        class: App\Factories\AliceLoaderFactory
        arguments:
            - '@fidry_alice_data_fixtures.doctrine.persister_loader'

    # =========== Split into separate files ========== #
    riftrun.abstract.repository:
        abstract: true
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        public: false

    riftrun.abstract.form_factory:
        abstract: true
        arguments:
           - '@form.factory'