parameters:
services:
    _defaults:
        public: false
        autowire: true

    _instanceof:
        App\Services\QueryService:
            public: true
        App\Command\Handlers\LoadFixturesCommandHandler:
            public: true
            tags:
                - { name: tactician.handler, command: App\Command\Commands\LoadFixtures }
        App\Command\Handlers\DatabaseClearCommandHandler:
            public: true
            tags:
                - { name: tactician.handler, command: App\Command\Commands\ClearDatabase }

        Twig_ExtensionInterface:
            tags: ['twig.extension']

        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags: ['kernel.event_subscriber']