RiftRunBundle\Model\CharacterType:
    type: entity
    table: charactertype
    repositoryClass: RiftRunBundle\ORM\Repository\CharacterTypeRepository
    manyToOne:
        searchQuery:
            targetEntity: SearchQuery
            inversedBy: characterType
            joinColumn:
                name: searchquery_id
                referencedColumnName: id
            cascade: [ persist ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
    lifecycleCallbacks: {  }
