RiftRunBundle\Model\CharacterClass:
    type: entity
    table: characterclass
    repositoryClass: RiftRunBundle\ORM\Repository\CharacterClassRepository
    manyToOne:
        searchQuery:
            targetEntity: SearchQuery
            inversedBy: characterClass
            joinColumn:
                name: searchquery_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
    lifecycleCallbacks: {  }
