RiftRunBundle\Model\GameType:
    type: entity
    table: gametype
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        gametype: GameType
        grift: Grift
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
