RiftRunBundle\Model\Grift:
    type: entity
    table: null
    fields:
        level:
            type: string
            length: 255
            comment: "40+, 50+, 60+, 1%"
    lifecycleCallbacks: {  }
