RiftRunBundle\Model\Post:
    type: entity
    table: posts
    repositoryClass: RiftRunBundle\ORM\Repository\PostRepository
    oneToOne:
        player:
            targetEntity: Character
            joinColumn:
                name: player_id
                referencedColumnName: id
                nullable: true
            fetch: LAZY
            cascade: [ persist ]
        query:
            targetEntity: SearchQuery
            joinColumn:
                name: searchquery_id
                referencedColumnName: id
                nullable: true
            fetch: LAZY
            cascade: [ persist ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetimetz
            gedmo:
                timestampable:
                    on: create
    lifecycleCallbacks: {  }
