RiftRunBundle\Model\Post:
    type: entity
    table: posts
    repositoryClass: RiftRunBundle\ORM\Repository\PostRepository
    oneToOne:
        player:
            targetEntity: Character
            joinColumn:
                name: player_id
                referencedColumnName: id
        query:
            targetEntity: SearchQuery
            joinColumn:
                name: searchquery_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetimetz
    lifecycleCallbacks: {  }
