RiftRunBundle\Entity\SearchQuery:
    type: entity
    table: searchquery
    repositoryClass: RiftRunBundle\ORM\Repository\SearchQueryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        minParagon:
            type: integer
            column: MinParagon
        createdAt:
            type: datetimetz
    lifecycleCallbacks: {  }
