RiftRunBundle\Model\SearchQuery:
    type: entity
    table: searchquery
    oneToOne:
        game:
            targetEntity: GameType
            joinColumn:
                name: gametype_id
                referencedColumnName: id
            fetch: EAGER
            cascade: [ persist ]
    oneToMany:
        characterType:
            targetEntity: CharacterType
            mappedBy: searchQuery
            fetch: EAGER
            cascade: [ persist ]
    repositoryClass: RiftRunBundle\ORM\Repository\SearchQueryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        minParagon:
            type: integer
            column: MinParagon
    lifecycleCallbacks: {  }
