RiftRunBundle\Model\SearchQuery:
    type: entity
    table: searchquery
    oneToOne:
        game:
            targetEntity: GameType
            joinColumn:
                name: gametype_id
                referencedColumnName: id
                onDelete: CASCADE
            fetch: EAGER
            cascade: [ persist ]
    oneToMany:
        characterType:
            targetEntity: CharacterType
            mappedBy: searchQuery
            fetch: EAGER
            cascade: [ persist, remove, merge ]
    repositoryClass: RiftRunBundle\ORM\Repository\SearchQueryRepository
    id:
            id:
                type: uuid
                id: true
                generator:
                    strategy: CUSTOM
                customIdGenerator:
                    class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        minParagon:
            type: integer
            column: MinParagon
    lifecycleCallbacks: {  }
