parameters:
services:
    _defaults:
        public: false
        autowire: true

    _instanceof:
        Twig_ExtensionInterface:
            tags: ['twig.extension']

        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags: ['kernel.event_subscriber']

    App\:
        resource: '../src/{Services,CommandBus/Handlers,Command/Handlers}'
    App\UI\Rest\Controller\:
        resource: '../src/UI/Rest/Controller'
        public: true
        autowire: true