App\Domain\Player\Model\Player:
    properties:
        type:
            - NotBlank: ~
            - NotNull: ~
            - Choice:
                choices: ["demon hunter", "monk", "wizard", "witch doctor", "barbarian"]
                message: "Wrong value"
        paragonPoints:
            - NotBlank: ~
            - NotNull: ~
            - Type:
                type: integer
            - Regex:
                pattern: '/^\d+$/'
            - GreaterThan:
                value: 1
        battleTag:
            - NotBlank: ~
            - NotNull: ~
            - Type:
                type: string
            - Regex:
                pattern: '/^#\d{4}$/'
        region:
            - NotBlank: ~
            - NotNull: ~
            - Choice:
                choices:  [EU, NA, AUS, ASIA]
        seasonal:
            - NotNull: ~
            - Choice:
                choices:  [0, 1]
        gameType:
            - NotBlank: ~
            - NotNull: ~
            - Choice:
                choices:  [hardcore, softcore]