App\Domain\Post\Model\Post:
    properties:
        player:
            - NotBlank: ~
            - NotNull: ~
            - Type:
                type: App\Domain\Player\Model\Player
        query:
            - NotBlank: ~
            - NotNull: ~
            - Type:
                type: App\Domain\SearchQuery\Model\SearchQuery