RiftRunBundle\Model\Character:
    properties:
        battleTag:
            serialized_name: battleTag
        paragonPoints:
            serialized_name: paragonPoints
    relations:
        -
            rel: self
            href:
                route: get_wizard
                parameters:
                    id: expr(object.getId())
