RiftRunBundle\Model\Character:
    properties:
        id:
            type: string
        battleTag:
            serialized_name: battleTag
        paragonPoints:
            serialized_name: paragonPoints
        createdAt:
            serialized_name: createdAt
        gameType:
            serialized_name: gameType
    # relations:
    #     -
    #         rel: self
    #         href:
    #             route: get_post
    #             parameters:
    #                 id: expr(object.getId())
    #             absolute: true
