RiftRunBundle\DTO\CharacterTypeDTO:
    exclusion_policy: ALL
    properties:
        id:
            type: string
            exclude: false
        type:
            serialized_name: type
            exclude: false