RiftRunBundle\DTO\PostDTO:
    properties:
        id:
            type: string
        createdAt:
            serialized_name: createdAt
    relations:
        -
            rel: self
            href:
                route: get_post
                parameters:
                    id: expr(object.id)
                absolute: true