RiftRunBundle\Model\Post:
    properties:
        createdAt:
            serialized_name: createdAt
    relations:
        -
            rel: self
            href:
                route: get_post
                parameters:
                    id: expr(object.getId())
                absolute: true
