RiftRunBundle\Model\SearchQuery:
    properties:
        minParagon:
            serialized_name: minParagon
        createdAt:
            serialized_name: createdAt
        characterType:
            serialized_name: characterType
