RiftRunBundle\Model\SearchQuery:
    properties:
        minParagon:
            serialized_name: minParagon
        createdAt:
            serialized_name: createdAt
        characterClass:
            serialized_name: characterClass
