RiftRunBundle\DTO\CharacterTypeDTO:
    properties:
        type:
            - NotBlank: ~
            - NotNull: ~
            - Choice:
                choices: ["demon hunter", "barbarian", "wizard", "witch doctor", "monk"]