RiftRunBundle\Model\Grift:
    properties:
        level:
            - NotBlank: ~
            - NotNull: ~
            - Type:
                type: string
            - Choice:
                choices: ['10+', '20+', '40+', '50+', '60+', '70+', '0+']
