#RiftRunBundle\Model\Post:
#    properties:
#        player:
#            - NotBlank: ~
#            - NotNull: ~
#            - Type:
#                type: object
#        query:
#            - NotBlank: ~
#            - NotNull: ~
#            - Type:
#                type: object
#
