RiftRunBundle\Model\SearchQuery:
    properties:
        minParagon:
            - NotBlank: ~
            - NotNull: ~
        characterType:
            - Valid: ~
            - All:
                - NotNull: ~
                - NotBlank: ~
            - Count:
                min: 1
                max: 4
