App\Domain\SearchQuery\Model\SearchQuery:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: App\Domain\SearchQuery\ValueObject\SearchQueryId
            groups: [Identifier]
        minParagon:
            expose: true
            serialized_name: minParagon
            groups: [Basic]
        playerCharacters:
            expose: true
            type: ArrayCollection<App\Domain\PlayerCharacter\Model\PlayerCharacter>
            accessor:
                getter: getPlayerCharacters
            serialized_name: playerCharacters
            groups: [Basic]
        gameMode:
            expose: true
            serialized_name: gameMode
            groups: [Basic]
            type: App\Domain\GameMode\Model\GameMode