App\Domain\PlayerCharacter\Model\PlayerCharacter:
    type: entity
    table: playercharacter
    manyToOne:
        searchQuery:
            targetEntity: App\Domain\SearchQuery\Model\SearchQuery
            inversedBy: playerCharacter
            joinColumn:
                name: searchquery_id
                referencedColumnName: id
                onDelete: "SET NULL"
            fetch: LAZY
    id:
        id:
            type: playerCharacterId
            id: true
            nullable: false
    fields:
        type:
            type: string
            length: 255
    lifecycleCallbacks: {  }
