App\Domain\Player\Model\Player:
    type: entity
    table: player
    id:
        id:
            type: playerId
            id: true
            nullable: false
    fields:
        type:
            type: string
            length: 255
            comment: "wizard, dh, wd, crusaider"
        paragonPoints:
            type: smallint
            comment: "number of current paragon points"
        battleTag:
            type: string
            length: 255
            comment: "Blizzard battle tag #11111"
        region:
            type: string
            length: '3'
            comment: "EU, NA"
        seasonal:
            type: boolean
            comment: "Is it seasonal or not"
        gameType:
            type: string
            length: 255
            comment: "hardcore, softcore"
    lifecycleCallbacks: {  }
