<?php

namespace RiftRunBundle\ORM\Repository;

/**
 * CharacterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
