<?php

namespace RiftRunBundle\ORM\Repository;

/**
 * SearchQueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchQueryRepository extends \Doctrine\ORM\EntityRepository
{
}
